export { buildMetadataCollection } from './metadata'
export { buildDataUkCollection } from './dataUk'
export { buildDataEnCollection } from './dataEn'
export { buildDataHeCollection } from './dataHe'
export { pagesCollection } from './pages'